language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4

  # MULTILINGUAL MODEL (PyTorch only)
- name: LanguageModelFeaturizer
  model_name: "distilbert"
  model_weights: "distilbert-base-multilingual-cased"

- name: DIETClassifier
  epochs: 80
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 60

policies:
- name: RulePolicy
assistant_id: 20260107-124210-formal-vocal
